version: '2.2'
services:
  stats-server:
    build: ./stats-server
    container_name: stats-server
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stats-server
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  main-server:
    build: ./main-server
    container_name: main-server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main-server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - STATS_SERVER_URL=http://stats-server:9090


  main-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "5434:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=main-server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
